FROM node:8.15.0-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ADD . /app
RUN npm install --silent
RUN npm run build

FROM nginx:1.14

COPY --from=build /app/dist /usr/share/nginx/html
